### ISSUE TITLE
Current state of Radio Buttons

### ISSUE THREAD

**Issue by sabian2008** [casperin/nod#101]
Hello dev. First of all, I want to both congratulate and thank you for this plugin. Easy to set up, quite complete and customizable. It's great, at least for someone like me doing an amateur non-profit website to have such a tool for free.

The issue, I'm having, which is not quite an issue but a lack of documentation maybe, is that I can't make radio buttons work. According to the latest pull, you've added an example, which I cannot find. Reading the documentation, I saw that 'some-radio' tries to match the selector so I tried to approaches, non of them worked. One was to add an id to the parent div containing all the "<input type=radio>", which failed horribly and use 'some-radio' (which I had expected). The other one was to add the same class to every radio button and then try the same validate option (some-radio). This time the page doesn't break on load, but when I click one radio, it displays error messages below every other radio but the clicked one and doesn't validate.

So perhaps before posting code in jsfiddle, I should ask you for the URL of the 'some-radio' example (sorry if its location is obvious, but I really couldn't find it). 

Thanks a lot for your time and the effort you are putting into this.

BTW: The plugin rewrite was awesome. It's really simple to configure and use now.

**Comment by casperin** [comment]
Hi @sabian2008, thanks for using my little library. It's nice when a little hobby project actually sees some usage.

I don't think there is one to be honest. Radio buttons reeeaally painful to validate properly, so I think made a pretty simple implementation.

I'm looking at a fiddle myself right now though, and it does seem like I got something wrong. I'll get back to you, but I'm pretty sure that it's a legit bug :)

**Comment by casperin** [comment]
Should work now. Basically you have to add a class to every single radio element (adding it to just the container would break the consistency), children are of course allowed in the selector. Like:

```javascript
myNod.add({
    selector: '.radio-parent input',
    validate: 'some-radio',
    errorMessage: '...'
});
```

Notice though, that the error message is kind of brutal. It shows an error for every single input. :-/

**Comment by casperin** [comment]
I wasn't quite happy with the three message problem, and thought about how to solve it. Here's a working solution for you, with just one message showing up :)

https://jsfiddle.net/uruc8v8a/

Just ignore the "Hello" message. It's just there to show that whatever content in that div will be deleted.

Just a FYI: there's another "bug" that forces you to call `setMessageOptions` after having added the elements (otherwise you're trying to set options for non-existing elements).

**Comment by sabian2008** [comment]
Thanks a lot for the feedback. It's really awesome when you have problems with a library someone's developing as a hobby and that person gets back to you in a matter of one or two days. Even better with such a complete answer!

I'm with little time right now, but during the week I'll try the fix and the approach you've described and get back with the results.

Thanks =)

**Comment by casperin** [comment]
I'm usually faster than 2 days actually. But I'm starting to see this girl you know... ;)

Thanks for reporting the bug. Let me know how it goes :)

**Comment by sabian2008** [comment]
Situation update:

Radio validation works just as expected, although in my case I had to replace plain input for input[type="radio"]. However, the message span hack doesn't work. I'll remove the excedent errors and when my humble site is online, I'll get back to you with the URL, as due to untidy code it's difficult to make a jsfiddle example of my situation (I tried and faild miserably).

Thanks

**Comment by casperin** [comment]
I'm not entirely sure what you expect to happen? Nod won't run a check on elements unless someone interacts with it. But as soon as you interact with the elements in your example you either are making it valid (by clicking one of the buttons), or you are submitting the form. Unless you tell nod to prevent submitting a form with errors it will just go ahead and do that.

If you add it, it seems to work just fine: https://jsfiddle.net/wedc9szs/1/

Or you can force it to perform checks right away to display the error message before you interact with it: https://jsfiddle.net/wedc9szs/2/

**Comment by sabian2008** [comment]
Sorry for the delay. 

I managed to implement your solution for the unique message. I had first tried to define an array of keys (I mean [{},{}] as you define rules) and then while reducing to test-case of one radio, had left the brackets. The thing is, it works, but as you can imagine for what I've just said, it seems you have to write one setMessageOptions instance for each radio group (or for each rule in general). It would make a nice addition to let setMessageOptions handle arrays of keys instead of just keys, if it ain't difficult. Otherwise, a few extra lines never killed anyone :P 

On the other hand, I found a little "bug". It would be nice if rules whose validate field depends on another selector, check for its field. In concrete, let's say you have an e-mail and a verify e-mail field. If you first leave blank e-mail field, then go to verify, leave blank, and then write the e-mail field, form will validate and submit button will be enabled. Perhaps it would be better if script would first see if validator's selector has a rule on itself and if that rule ain't accomplished, the "son" validator returns false, even if the same-as (or some other) condition, is satisfied. I know this can be accomplished with the plugin if I wish to do so, it's just my idea of a default behaviour right now. 

In any case, these two, are very little observations. As I've already stated, the plugin is great. It saves A LOT of time for us, people who want a small silly form to be validated, and it's implemented in a very elegant way and extremely easy to use, understand and debug.

**Comment by casperin** [comment]
The first one, is a definite must-do. Well caught. I already implemented it.

The second one is very far from trivial. I just had a shot at it right now, but it actually forces a check function (which should know as little about anything as possible) to do a check on the element itself, to check its status. Only problem is, it doesn't have access to the specific instantiation of nod (`myNod.getStatus(options.element)` somewhere around [line 1121](https://github.com/casperin/nod/blob/master/nod.js#L1121), so it can't really. And it shouldn't.

But you can see, that the `same-as` element is being checked. It just bails out early because it doesn't contain any value ([line 1125](https://github.com/casperin/nod/blob/master/nod.js#L1125)).

Thanks for your feedback though :) Very valuable! And again, I'm happy to hear that it's actually solving real people's problems.
