### ISSUE TITLE
CustomEvent needs polyfill in ie

### ISSUE THREAD

**Issue by casperin** [casperin/nod#103]
Either find another way to send events, or use this: https://github.com/krambuhl/custom-event-polyfill/blob/master/custom-event-polyfill.js

(Thanks Andy)

**Comment by andy-hook** [comment]
Happy to see you raise this, if I encounter anything else I'll submit an issue here.

**Comment by casperin** [comment]
And good to see you on Github :)

**Comment by casperin** [comment]
Only took me two months to do :P It's done now. I basically just added the polyfill.
