### ISSUE TITLE
min-number validation bug

### ISSUE THREAD

**Issue by bocahptualang** [casperin/nod#105]
minimum number validation not working as expected, i add validation configuration:

myNod.add([ {
                selector: document.getElementById('bar'),
                validate: 'min-number:5',
                errorMessage: 'Minimum value is 5'
            }]);

but it accept 1,2,3,4,5 and reject 6,7,8,9,...

**Comment by casperin** [comment]
Ouch. Good catch. See [line 1014 - 1024](https://github.com/casperin/nod/blob/master/nod.js#L1014-L1024) in nod.js. The two check are identical.

```js
    'max-number': function (maximumNumber) {
        return function maxNumber (callback, value) {
            callback(+value <= maximumNumber);
        };
    },

    'min-number': function (minimumNumber) {
        return function minNumber (callback, value) {
            callback(+value <= minimumNumber);
        };
    },
```

**Comment by casperin** [comment]
Fixed :) Thanks for reporting.
