### ISSUE TITLE
Error using noDom mode and calling nod.remove(); on input

### ISSUE THREAD

**Issue by andy-hook** [casperin/nod#106]
Having an issue where nod is trying to find an error span when calling nod.remove(), it can't find it because i'm using noDom mode. If I set noDom to false I no longer receive this error.

'Uncaught TypeError: Cannot read property 'removeChild' of null'

Originates from this condition

        // Then we remove the span if it wasn't one that was set by the user.
        if (!customSpan) {
            span.parentNode.removeChild(span);
        }

**Comment by casperin** [comment]
Sorry about the delay there. Been caught in stuff. With that info it would have been super easy for you to do a pull request on it Andy ;) Regardless, I fixed it now with https://github.com/casperin/nod/commit/a5240b660be0d11f2b226ad05066682aa77ae21a

**Comment by andy-hook** [comment]
Yes you're right, I'm new to github contributions and will make an effort for small tweaks like this in the future! Thanks for fixing.

**Comment by casperin** [comment]
:+1:
