### ISSUE TITLE
disableSubmit doesn't work with multiple submit buttons

### ISSUE THREAD

**Issue by puma10** [casperin/nod#108]
When having multiple submits the disableSubmit only works on the first submit. 

Here is my configuration. 

myNod.configure({
    // parentClass: 'form-group'
    submit: '.form-submit',
    disableSubmit: true,
    form: '#add_product_form',
    preventSubmit: true,
    successClass: 'has-success',
    errorClass: 'has-error',
    errorMessageClass: 'help-block',
});

<img width="876" alt="2015-07-10_2324" src="https://cloud.githubusercontent.com/assets/6099078/8621974/2baa21f4-275b-11e5-8f6a-bc629a877190.png">

**Comment by casperin** [comment]
Yeah, that's entirely on purpose actually. I'm on my way on vacation (w/o internet) for a week, so I won't be fixing it until I get back. You can hotfix your own fork if you want. Basically go to https://github.com/casperin/nod/blob/master/nod.js#L279 and change it to something like:

```javascript
nod.getElements(configuration.submit).forEach(function (submitButton) {
    submitButton.disabled = !areAll(nod.constants.VALID);
});
```

... or you can wait until I get home. :-)

**Comment by casperin** [comment]
So that turned out to be a long holiday! From this repository anyway. Shame on me.

I hope you worked it out. If not, I did exactly what I described above and it's in release 2.0.11. :+1:
