### ISSUE TITLE
set a single field as invalid

### ISSUE THREAD

**Issue by mattiaocchiuto** [casperin/nod#112]
Hello I'm try to figure out how I can set a field as invalid pragmatically by javascript.

**Comment by casperin** [comment]
@mattiaocchiuto. Did you find out? I have not looked at nod for quite a while (hence, no responding), so I honestly don't remember if it's possible.

I see now that you've done a pull request. Love it. I'll go through the rest of the notifications I haven't looked at, and then I'll probably merge it in. Just glanced over the code. Looks good. :metal:
