### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by tuelsch** [casperin/nod#116]
Hey, it seems that versions 2.0.4 and 2.0.10 are not published on npm.

**Comment by casperin** [comment]
That is probably true. I feel every time I make an update that there's a thousand things that needs to happen (git version, npm, tests, etc). I would not be surprised if I forgot that.

I haven't looked at `nod` for quite a while now, so I'll go through some issues, some pull requests, then update and put the latest on npm for you.

Thanks for pointing it out to me. :beers:

**Comment by casperin** [comment]
Hep! Done. :muscle:

**Comment by tuelsch** [comment]
Hey, thanks a lot for your effort, looking forward to using nod!

Happy new year
