### ISSUE TITLE
ReadMe should clarify bootstrap 3

### ISSUE THREAD

**Issue by KelseyDH** [casperin/nod#117]
Tried this on Bootstrap 2 and realized the css has been updated to support Bootstrap 3 only.  Would be nice to have a way to switch the css between versions.

**Comment by casperin** [comment]
You can actually [define the class names that nod uses yourself](https://github.com/casperin/nod#classes) which should solve your issue, but I suppose I could have made a shorthand to do it for you, or documented it.

I am pretty sure I only had Bootstrap (and jQuery) in mind when writing v.1.x, so such a shorthand is out of the question now, but you're very welcome to do a pull request with an update to the docs.
