### ISSUE TITLE
Is it possible to write "depends" style validation and control order of validation checks?

### ISSUE THREAD

**Issue by JesusCarvalho** [casperin/nod#120]
I have tried many js libs looking for a DRY way to write validations that:

1] target multiple fields 
2] allow me to control what order the validations are checked in
3] allow me to write "depends" style validations, ex: "All-or-nothing": all fields in div can be empty but if any are filled then *all* must be filled.

I'm using Rails/Bootstrap, can you help me understand how much effort is required for numbers 2 and 3 above if I'm using nod.js

Thanks
TJ

**Comment by casperin** [comment]
1. Absolutely no problem.
2. I am not sure what you mean. They are usually checked when the user leaves the input field or has stopped typing for x amount of milliseconds. You can also disable all that and check upon form submit. In that case, I guess they'll each be checked in the order that they were added.
3. No problem. You can either give it the function you wish to use for checking the field, or you can define it somewhere in your code and just access it globally like any predefined function.

nod.js does not care what framework or libraries you are using; but I originally wrote it with bootstrap in mind; so it definitely will work for that.
