### ISSUE TITLE
Is it possible to use more than 1 rule in the validate property?

### ISSUE THREAD

**Issue by bersujamu** [casperin/nod#121]
I can't find the usage of multi rules on documentation. Could we use something like this:

```
var myNod = nod();

myNod.add([{
    selector: '.name',
    validate: ['presence', 'min-length:3'], // multi rules
    errorMessage: 'Don\'t leave empty.'
}
```

**Comment by casperin** [comment]
It's been a while since I've worked on this; but as far as I remember it goes something like:

```js
myNod.add([{
    selector: '.name',
    validate: ['presence', 'min-length:3'], // multi rules
    errorMessage: ['Don\'t leave empty.', 'Should be at least 3 characters long']
}
```

ie. you need multiple error message. Have a look here: https://github.com/casperin/nod/blob/master/nod.js#L80
