### ISSUE TITLE
Using jQuery makes all events disappear when nod.remove is used

### ISSUE THREAD

**Issue by tigermarques** [casperin/nod#127]
When using nod alongside jQuery, I noticed that the following lines of code don't work as well as they should:
```
function dispose () {
    element.removeEventListener('input', changed, false);
    element.removeEventListener('change', changed, false);
    element.removeEventListener('blur', changed, false);

    if ($element) {
        $element.off();
    }

    if (triggerEvents) {
        triggerEvents.forEach(function (eventName) {
            element.removeEventListener(eventName, changed, false);
        });
    }
}
```

When events are removed this way, all other event handlers I may have put on the element will also be removed.

A possible solution might be to use [jQuery namespaced events](http://api.jquery.com/event.namespace/)

**Comment by casperin** [comment]
hmm you are right. I remember looking into this, and I actually thought that I implemented it.

I kind of stopped development on this project (last commit was like a year ago); so to be brutally honest there's very little chance that I'll ever fix this. I'd love a pull request though, and I'll do what I can to make it go through :)

**Comment by casperin** [comment]
@tigermarques, @chall8908 did the work. It's on the `develop` branch for now, but I'll merge it into `master` soon.

**Comment by tigermarques** [comment]
Awesome, thanks a lot!
Thank you @chall8908!!
