### ISSUE TITLE
Home page link broken.

### ISSUE THREAD

**Issue by kanakiyajay** [casperin/nod#94]
http://casperin.github.io/nod/ gives 404 error.

**Comment by casperin** [comment]
Where did you find that? I thought I'd delete all references to it. Maybe externally?

**Comment by casperin** [comment]
Thanks for the heads up :)

**Comment by kanakiyajay** [comment]
I curate content for this site : http://jquer.in/jquery-plugins-for-html5-forms/nod/ and get alerts whenever a link gives a 404 error.

**Comment by casperin** [comment]
Oh. Thanks for including me on your website. I like how it fetches the readme and adds it to the description.

I put a placeholder site on the page now (I suspect that you're not the only one linking to it), and I'll add something better with examples and stuff later.
