### ISSUE TITLE
Don't show error/ok messages

### ISSUE THREAD

**Issue by casperin** [casperin/nod#95]
Don't actually show the message, but rather fire off an event on the element with the relevant info.

This is so it's possible to just listen to the element. Something like:

```javascript
$(element).on('nod.error', function (event) {
    // Show my own error somehow
});

// Where `event` is something like...
event = {
    element: element, // the dom element
    status: 'invalid' // or 'valid',
    errorMessage: 'Not a valid number'
}
```

**Comment by casperin** [comment]
Done. Undocumented for now, but done. Used by passing `noDom = true` to configure:

```javascript
myNod.configure('noDom', true);
```

and then listening on the elements to `nod.validation`.

```javascript
document.getElementById('myElement').addEventListener('nod.validation', console.log.bind(console), false);
```

**Comment by andrewspiesdreamsmiths** [comment]
@casperin Hey man, I realise this message comes many years later, but was this ever extended in the library?

Also having trouble logging the results of 'nod.validation' event. 

I have a validate function and in it I'm iterating over the elements.

Code below: 
```javascript 
let form = document.getElementById(id);
let formdata = new FormData(form);
let entries = formdata.entries();

for (let entry of entries) {
    let el = document.getElementById(entry[0]);
    el.addEventListener('nod.validation', console.log(event), true);
}
```
Does this seem right?

**Comment by casperin** [comment]
Oh damn man, this is years and years old. I had no idea people were still using this.

Well you definitely have a bug in that code, but I imagine it's just a typo. Your "last" line should probably be
```js
el.addEventListener('nod.validation', event => console.log(event), true);
```
I didn't know the `FormData` api, but reading about it on mdn, it seems to give you key/value pairs, that is name/value pairs, not id/value pairs. Have a look at this codepen: https://codepen.io/anon/pen/GPKGRp?editors=1011

I'd check if the `el` is what you think it is; and if it is, then it's probably a bug in this library. And unfortunately, one that I am very unlikely to fix (sorry).
