### ISSUE TITLE
need massCheck function capability

### ISSUE THREAD

**Issue by wsugiri** [casperin/nod#96]
is there any function like massCheck in new version like old version?

**Comment by casperin** [comment]
To be honest I don't quite remember what exactly it did, but I imagine it did something like this: https://github.com/casperin/nod#manually-checking-validity

```javascript
myNod.areAll('valid');
```

Will that work for you?

**Comment by wsugiri** [comment]
thank you for the function, but not exactly same with massCheck.
in old version massCheck, we can get both the result and update the screen to (give visual error).
function myNod.areAll('valid') only get the result valid or not.

by the way thank you for the feature.

**Comment by casperin** [comment]
Aaaah right.. it would basically trigger a change on every element, forcing nod to run its checks.

I guess there is no equivalent to that, sorry.

**Comment by wsugiri** [comment]
never mind, my team already get the work around by modify the checkers and add equivalent capability.

thanks.

**Comment by casperin** [comment]
Glad to hear that :) And thanks for using my little library

**Comment by wsugiri** [comment]
yes.., your library save me a lot of time to manage validation.
for trigger visual element, we add little code to make massChange capability

```js
    function massCheck () {
        checkers.forEach(function(checker) {
            checker.performCheck();
        })
    }
```
then this feature available in the latest version, my be the next release you will add this capability. thanks...

**Comment by casperin** [comment]
Hmm, yeah. I might do that. Why not. Different name though I think. `checkAll()` or something. I'll keep it in mind :)

**Comment by casperin** [comment]
https://github.com/casperin/nod#force-nod-to-perform-a-check :)

**Comment by wsugiri** [comment]
That's great, thank you for the implementation.

**Comment by wsugiri** [comment]
That's great, thank you for the implementation and fast response.

**Comment by wsugiri** [comment]
That's great, thank you for the implementation and fast response.
