### ISSUE TITLE
Making jQuery event work with nod

### ISSUE THREAD

**Issue by lucmazon** [casperin/nod#97]
Hello,

I couldn't make the jQuery **trigger('change')** work when modifying an input field with jquery **val('value')**.
This seems to be related to the problem described in this ticket: http://bugs.jquery.com/ticket/11047

Here's a simple example showing the problem : http://jsfiddle.net/404xxouw/2/

I get that it's more a jQuery issue than a nod one, but seeing how jQuery is widely used, would there be a way to make nod work seemlessly with jQuery ? (I'm not good enough in javascript to now if it's possible or not ^^).

Thanks a lot!

**Comment by casperin** [comment]
Hi. :) You are exactly right, except it isn't really a bug in jQuery, but rather a conscious choice on their part. That sucks, but I can definitely understand them. Thanks for bringing it to my attention.

The only real option I see, is to detect whether jQuery is present, and if so, use its event system to listen for jQuery changes. It's not pretty, but it should work.

However, even this solution has its limitations (even though I already use it in `.getElements()`), which is that of relying on a global variable being present. The user may have renamed it (to avoid conflicts maybe), or it may be part of a bigger app where everything is being required in the individual files. So maybe the right option would be to add something like

```javascript
var myNod = nod({jQuery: $});
```

to explicitly let nod.js know that it's okay to use jQuery, and where to find it.

I'll give this one some thought and get back to you. Thanks for using nod.js. It warms my heart to hear when my little project here solves actual problems for people. :)


Btw. I updated your example, to be a little easier to work with: http://jsfiddle.net/404xxouw/3/

**Comment by lucmazon** [comment]
Sorry I didn't issue a pull request myself, I'm definitely not good enough in javascript to modify properly your code :) But I think the solution of adding a configuration telling the library to use jquery is a good one !

**Comment by casperin** [comment]
Don't worry about that. It'll come. Your issue here was a good help for me. I'll do the rest ;)

**Comment by casperin** [comment]
I think I might like the idea of adding it as an argument. I could extend that to adding underscore if you want me to use underscore's `_.each` instead of `.forEach` if you want support for ie lower than 9.

**Comment by lucmazon** [comment]
You're right, that would be cool too ^^

**Comment by casperin** [comment]
Hep! Solved :) Check here:
https://github.com/casperin/nod#triggerevents

I decided to just go with the `configure` object, and then I added the possibility to just pass that in upon creation:

```javascript
var myNod = nod({
    delay: 400,
    jQuery: $
});
```

I also added https://github.com/casperin/nod#force-nod-to-perform-a-check (see issue #96) that you might find interesting (sort of does the same thing, but differently).

**Comment by lucmazon** [comment]
Awesome!  I'm actually using both functionalities now! Keep up the good work ;)

**Comment by casperin** [comment]
:+1: Good to hear.
